# Copyright © 2020 Amin NAIRI
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the “Software”), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

name: Heroku Deployment

on:
    push:
        branches:
            - next

jobs:
    heroku:
        name: Heroku Deployment
        runs-on: ubuntu-latest

        steps:
            - name: Checkout the project
              uses: actions/checkout@v2

            - name: Prepare the the context environment setup
              run: cp .env.example .env

            - name: Setup the Heroku API key
              run: sed -i 's/HEROKU_API_KEY=/HEROKU_API_KEY=${{ secrets.HEROKU_API_KEY }}/g'

            - name: Setup the Discord bot token
              run: sed -i 's/DISCORD_BOT_TOKEN=/DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }}/g'

            - name: Deploy the bot to Heroku
              run: make deploy
